rails/buildkite-config

docker-compose.yml
ref: https://github.com/rails/rails/pull/35698
I want to use this env var to skip generating test report because other CI may not support artifact
=> Expose BUILDKITE env var

pipeline-generate
ref: https://github.com/rails/rails/pull/35698#issuecomment-490568189
Sometimes buildkite agent was lost.
- https://buildkite.com/rails/rails/builds/61077#6e5a869c-bc99-4df4-ae9f-7433e2a39638
- https://buildkite.com/rails/rails/builds/61018#b5746af9-adf3-4e91-871b-a5af02b7ba72
I asked buildkite support team and I got this advice:
> Hey there Fumiaki — thanks for reaching out! 👋🏼
>
> Just looking into that particular job it seems that it exited with “Exited with status -1 (agent lost)”.
>
> Agent lost means that the agent process disappeared while processing the job — typically this shows up with autoscaling agents where they can come and go and be terminated by the autoscaling process.
>
> It’s possible to work around this with retry rules for steps that can detect this and run the step …
=> Retry if agent was lost

Dockerfile
Currently, Rails' build fails because `mysql-client` package does not found.
https://buildkite.com/rails/rails/builds/62162#29082d6b-4dc8-4888-97e4-d39094ac563e/249-339
It seems strech has `mysql-client`, but buster does not have `mysql-client`.
https://packages.debian.org/stretch/mysql-client
https://packages.debian.org/buster/mysql-client
As `default-mysql-client` that `mysql-client` depended on seems to be in both, so fixed to use that instead.
https://packages.debian.org/stretch/default-mysql-client
https://packages.debian.org/buster/default-mysql-client
=> Use `default-mysql-client` instead of `mysql-client`

pipeline-generate
For https://github.com/rails/rails/issues/36590.
https://hub.docker.com/r/rubylang/ruby/tags?name=nightly-bionic
The Ruby Docker image tags have been renamed to reflect the move from Subversion to Git: https://github.com/ruby/ruby-docker-images/pull/10
The latest build on the new tag includes this commit, which should get Rails' CI building again: https://github.com/ruby/ruby/commit/a569bc09e25a2ba813d0bec1228d9ff65330a3db
=> Use master-nightly-bionic Ruby Docker image tag

docker-compose.yml
The postgres image no longer starts by default without a password set:
https://github.com/docker-library/postgres/pull/658
Since this change, Rails' CI is failing on all postgresql steps:
https://buildkite.com/rails/rails/builds/67011
Setting `POSTGRES_HOST_AUTH_METHOD=trust` restores the old behaviour. It's roughly equivalent to `MYSQL_ALLOW_EMPTY_PASSWORD`, which we already set:
https://github.com/rails/buildkite-config/blob/f94d68290a44c5591587fe261135f862cb76209e/docker-compose.yml#L106-L107
=> Allow postgres container to start with no password

pipeline-generate
Feed the beast. Switch from waits to dependencies to start running steps as soon as images are built.
=> Wait less; depend more

pipeline-generate
Starting from Ruby 3, rubylang/ruby docker image uses Ubuntu focal by default.
Refer https://github.com/ruby/ruby-docker-images/pull/20
Confirmed it works without failures or errors.
```ruby
$ git clone https://github.com/rails/rails.git
$ cd rails
$ git clone https://github.com/rails/buildkite-config .buildkite/
$ RUBY_IMAGE=rubylang/ruby:master-nightly-focal docker-compose -f .buildkite/docker-compose.yml build base \
&& CI=1 docker-compose -f .buildkite/docker-compose.yml run default runner actionpack 'rake test'
... snip ...
Finished in 8.669211s, 388.9627 runs/s, 1887.2537 assertions/s.
3372 runs, 16361 assertions, 0 failures, 0 errors, 0 skips
```
=> Use `rubylang/ruby:master-nightly-focal` docker image

pipeline-generate
https://registry.hub.docker.com/v1/repositories/ruby/tags now redirects to https://hub.docker.com/v1/repositories/ruby/tags
Since `Net::HTTP.get` doesn't follow redirects by default, this is now breaking CI, eg. https://buildkite.com/rails/rails/builds/78494#a67e145d-d58b-40c2-8845-080fd4cadeea
=> Update dockerhub URL

Dockerfile
The latest Ruby Docker image upgraded Debian to Bullseye:
https://github.com/docker-library/ruby/pull/357
Bullseye no longer supports Node v10.x, which cause NPM to not be
installed, resulting in failing builds.
As Node v10.x is no longer supported we should switch to a supported
version. Active support for v14 ends in November 2021, so we might as
well switch to v16. See: https://endoflife.date/nodejs
Steps to reproduce:
$ git clone https://github.com/rails/rails
$ cd rails
$ git clone https://github.com/rails/buildkite-config .buildkite/
$ RUBY_IMAGE=ruby:3.0.2 docker-compose -f .buildkite/docker-compose.yml build base && CI=1 docker-compose -f .buildkite/docker-compose.yml run actionview runner actionview 'rake test:ujs'
=> Use Node v16.x as v10.x is no longer supported

pipeline-generate
The guides fail due to the test scripts for the bug report templates.
They don't always bundle but they aren't needed for applications to be
confident that 5-2-stable and 6-0-stable are passing CI.
=> Ignore guides for 6.0 and below

pipeline-generate
We want to skip guides on 6.0 and below. I got the configuration wrong
here in my last commit, it should be anything less than 6.1.
=> Fix config for guides

pipeline-generate
Reverts rails/buildkite-config#17
Discussed offline with Buildkite and now Rails CI runs https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.8.2 that uses Docker 20.10.14. 
Docker 20.10.14 should run `mariadb:latest` image that is MariaDB 10.8 without issues.
=> Revert "Use "mariadb:10.7" to workaround CI failure"

pipeline-generate
Currently we're only running mysql 8 builds which has resulted in
merging broken changes in mysql 5.7 that we end up finding when we run
tests locally. Running with both 8 and 5.7 will ensure that all new
features to active record are supported by both databases, or cases
where they aren't supported, we can handle those cases in PRs.
=> Add mysql 5.7 build

pipeline-generate
"rubylang/ruby:latest" actually runs the latest released version of Ruby like 3.1.3
Once https://github.com/rails/rails/pull/46711 has been merged to Rails main branch, "rubylang/ruby:master-nightly-focal" can proceed Rails CI to test Rails against Ruby 3.2.dev
=> Use "rubylang/ruby:master-nightly-focal" to test Ruby 3.2 dev

pipeline-generate
Ruby 3.2 has been released and `ruby:3.2` Docker image is available.
```ruby
$ docker run --rm -t ruby:3.2 ruby -v
... snip ...
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]
```
Refer to:
https://github.com/docker-library/official-images/pull/13806
https://github.com/docker-library/ruby/pull/399
=> Add Ruby 3.2

Dockerfile
On Rails 6-0-stable we're not able to build new Rubies (3.1+) because the version of Rubygems is too old. I do not understand why it's falling back but I hope this will fix the issue we're seeing.
Error message:
```
ERROR:  rubygems 3.2.9 is not supported on 3.3.0. The oldest version supported by this ruby is 3.3.3
ERROR:  rubygems 2.7.8 is not supported on 3.3.0. The oldest version supported by this ruby is 3.3.3
```
Build ex: https://buildkite.com/rails/rails/builds/92217#018587aa-6df9-40a4-bf5d-05772f425cc4
=> Bump minimum rubygems

docker-compose.yml, pipeline-generate
Run the action text integration tests on CI.
alt to https://github.com/rails/rails/pull/46842
Related ticket https://github.com/rails/rails/issues/46804
=> Add system tests for action text

pipeline-generate
Reverts rails/buildkite-config#30
Bundler 2.4.5 has been released that fixes https://github.com/rubygems/rubygems/pull/6285
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#245-january-21-2023
We should not need to lock/pin Bunder and RubyGems versions anymore.
=> Revert "Lock RubyGems and Bundler version"

pipeline-generate, runner
This is an alternative to #32 which passes the Rack version as an env var to Rails Gemfile.
Depends on rails/rails#47133
Example build here:
https://buildkite.com/rails/rails/builds/93029#0185e6dd-f7da-4149-b11a-fa1a29ef38f0
=> Use env for Rack 3 jobs for Gemfile

pipeline-generate
Rails 6.1.Z only provides the fix for security issues, not bug fixes we do not need to run bug_report_templates against Rails 6.1.z (6-1-stable branch) anymore.
This commit is based on the comment below:
https://github.com/rails/rails/pull/47411#issuecomment-1434041230
There was a similar pull request to skip guides for Rails 6.0. https://github.com/rails/buildkite-config/pull/16/files
=> Skip guides for Rails 6.1

pipeline-generate
We already don't actually use it, so this only reduces YJIT coverage of 'bundle install' -- which our suite is not well-equipped to exercise.
=> Skip building a separate YJIT image

pipeline-generate
The `mysql` gem was removed from Rails in 5.0 (see https://github.com/rails/rails/pull/22642). We needed to keep the builds around because at the time we still supported older versions with `mysql` for security and bug releases.
However, we haven't run a build for 4-2-stable (the last supported version) since 2020, so let's remove this from the buildkite config.
=> Remove obsolete mysql task

pipeline-generate
Starting with https://github.com/rails/rails/commit/a96d5beb63bbbecd9f63d21b7583edbd1f24da33 Rack 3.0 is the version of Rack tested by default. 
We want to continue testing with Rack 2.0 to make sure we don't introduce backward incompatible changes.
=> Rack 3.0 is the default, continue testing Rack 2.0 for compatibility

pipeline-generate
This pull request changes Ruby Docker images for 3.1 and 3.2 from Debian 12 "bookworm" based to Debian 11 "bullseye". Until we address the root cause of https://github.com/rails/rails/issues/48483
Refer to https://github.com/docker-library/ruby/pull/415
=> Use Debian 11 "bullseye" based Ruby Docker image

pipeline-generate
Reverts rails/buildkite-config#47
Since https://github.com/rails/rails/pull/48493 has been merged to Rails main branch, we do not have to worry about `MD4` digest is not supported in OpenSSL 3.0 now. Let's use the latest Debian "bookworm" based Ruby images.
=> Revert "Use Debian 11 "bullseye" based Ruby Docker image"

pipeline-generate
This commit runs `rake test:isolated` for Action Text once https://github.com/rails/rails/pull/46129 is merged.
=> Support `rake test:isolated` for Action Text

Dockerfile
Fix https://github.com/rails/rails/issues/48525
This commit uses Node v18 LTS from NodeSource to install `npm` and use the latest LTS for Rails CI.
Since the Ruby`ruby:3.1` and `ruby:3.2` base image has changedfrom Debian "bullseye" 11 based to "bookworm" 12 based one, this causes `actionview: rake test:ujs ERROR: 127'.` This `ERROR: 127` is thrown when no `npm` program is found in the path.
We use NodeSource http://deb.nodesource.com/node_16.x to install the `nodejs` version 16 apt package , which also installs `npm` as described below.
https://deb.nodesource.com/node_16.x/dists/bookworm/main/binary-amd64/Packages
> Provides: nodejs-dev, nodejs-doc, nodejs-legacy, npm
There is another `nodejs` package provided by Debian. The `nodejs` version provided for Debian bullseye 11 is 12 , which …
=> Install Node v18 LTS from NodeSource

buildkite-config-initial-pipeline.yml, rails-initial-pipeline.yml
Follow up to #45, we don't want to setup `commit`.
From the docs [[ref](https://buildkite.com/docs/pipelines/trigger-step#trigger-step-attributes)]:
> commit    The commit hash for the build.
> Default: "HEAD"
> Example: "ca82a6d"
Example build failure when set using `${BUILDKITE_COMMIT}`:
https://buildkite.com/rails/rails-ci/builds/3
```
Git checkout failed as commit c16105efdbda6c0ca6cb00d0d38cb7ff8fe6f7b0 could not be found in branch main
```
=> Don't set commit when triggering rails-ci builds

pipeline-generate
This pull request updates to use Ubuntu jammy based rubylang/ruby docker image because it is by default https://github.com/ruby/ruby-docker-images/pull/43
Confirmed it works without failures or errors.
```ruby
$ git clone https://github.com/rails/rails.git
$ cd rails
$ git clone https://github.com/rails/buildkite-config .buildkite/
$ RUBY_IMAGE=rubylang/ruby:master-nightly-jammy docker-compose -f .buildkite/docker-compose.yml build base \
&& CI=1 docker-compose -f .buildkite/docker-compose.yml run default runner actionpack 'rake test'
Finished in 3.572241s, 1006.9311 runs/s, 4739.3225 assertions/s.
3597 runs, 16930 assertions, 0 failures, 0 errors, 0 skips
```
I recall this when I was investigating https://github.com/rails/rails/issues/48483 and https://github.com/rails/rails/pull/48493 …
=> rubylang/ruby docker image uses Ubuntu jammy by default 

pipeline-generate
Similarly to actioncable integration, actionview ujs tests are executed in Saucelabs env that occasionally fails to start (e.g https://buildkite.com/rails/rails/builds/97407#0188e0b2-1402-4578-9214-6dfb0e26821f) so allowing retries for this seems to be reasonable.
=> Allow retries for actionview test:ujs

pipeline-generate
test:isolated was [enabled][1] for Action Text, but this has lead to failing builds on stable branches since the task only exists on the main branch
This fixes the issue by checking that the task exists before adding it to the pipeline
[1]: https://github.com/rails/buildkite-config/commit/b0431653b692006f64ab6a89e1e3b3101d778b67
=> Fix actiontext test:isolated on stable branches

pipeline-generate
While it appears to be cached for some steps, the checkout takes 20-30 seconds when it doesn't cache. Since all of the tests run inside docker images the checkout is unnecessary so it can be disabled to save the time.
When enabling this setting, Buildkite gets more strict over how the Docker images are built. Because of this, we have to provide the other compose service names in the "build-alias" field.
=> Skip checking out rails/rails in test steps

pipeline-generate
Reverts rails/buildkite-config#57
I suspect this change (specifically the aliasing bit) is causing https://github.com/rails/rails/issues/48701
I believe I've also incidentally fixed the needless-git-checkout issue on the build agents themselves, so _in theory_ we can now safely revert this without losing the performance gain.
=> Revert "Skip checking out rails/rails in test steps"

pipeline-generate, rails-initial-pipeline.yml
Buildkite have set up a dedicated agent pool for running image builds -- this change moves the relevant jobs to run on those agents.
The hope is that this will help builds to start faster, and also improve our ability to maintain some cached state between builds, as compared to the ephemeral runner instances.
=> Move builds (and pipeline) into new "builder" queue

runner
I don't remember why I put these here, and they seem to confuse log timing in the UI.
=> Don't write empty log groups

pipeline-generate
We introduced support for RACK=head with https://github.com/rails/rails/commit/8adc374e74d5438dfb95508c108a465710f54e82.
This allows us to test it allowing soft failures.
=> Test against rack head

.gitignore, Gemfile, Gemfile.lock, Rakefile, buildkite-config-initial-pipeline.yml, lib/buildkite_config.rb, lib/buildkite_config/annotate.rb, lib/buildkite_config/diff.rb, pipeline-generate, test/buildkite_config/test_annotate.rb, test/test_helper.rb
Adds the diff of generated pipeline to the buildkite annotations:
[[Example](https://buildkite.com/zzak/buildkite-config/builds/163)]
---
This step occurs _after_ the approval prompt since we are evaling user input directly to the ruby interpreter. It doesn't fail or anything if there are changes.
My goal is to use this diff as a baseline for refactoring, to avoid accidental breakage to the generated pipeline unintentionally.
=> Add buildkite-config diff tool

Dockerfile
Fixes rails/rails#50524
The old nodesource repository is no longer being updated, which is why the debian node version is now higher than nodesource's (and debian's nodejs package does not install npm, hence the missing npm issue).
Followed the instructions here to setup the new repository: https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository
=> Fix missing npm by migrating to new nodesource

Dockerfile
See rails/rails#50535
This makes running `yarn build` from the 'actionview' directory optional, as the machinery for building and testing rails-ujs will be removed.
=> Make 'yarn build' from actionview optional

Rakefile, buildkite-config-initial-pipeline.yml, lib/buildkite_config/annotate.rb, lib/buildkite_config/diff.rb, pipeline-generate-nightly, rails-nightly-initial-pipeline.yml, update-initial-pipelines
All those steps takes a lot of time and we don't have a lot of agents. Since we don't need to run those every single change, remove them from the main pipeline.
=> Move Ruby master and YJIT to a nightly build pipeline

Dockerfile, await-all, docker-compose.yml, pipeline-generate
This change came out of originally trying to run our CI locally on my M1 macbook.
Since the [await](https://github.com/betalo-sweden/await) script we're using only works on amd64, and is unmaintained, I tried to find an alternative. Many of the similar libraries (dockerize, etc) also only offer x86 binaries, with many going unsupported since docker-compose added health check support.
If you look around at some of their issue trackers, you will see several people who have either forked and built their own binary for arm, or just started using docker-compose health checks.
I think this is a better long term approach, and gets us able to run on arm machines, which maybe a cheaper alternative in the future.
=> Replace await script with docker-compose health checks

docker-compose.yml
Since updating the MySQL healthcheck to use mysqladmin, there has been an increase in failing buildkite jobs that report being unable to connect to MySQL. This behavior is consistent with reports on stackoverflow that the mysqladmin check is unfortunately not a reliable way to know whether the database is ready for connections.
This commit changes the MySQL healthcheck to be a `SELECT 1;` query. This should ensure that the MySQL is not only started but additionally ready for connections before reporting as healthy. Additionally, the interval for the healthcheck was reduced to 1s so that it has the potential to pass faster instead of only in 10s intervals.
stackoverflow: https://stackoverflow.com/questions/42567475/docker-compose-check-if-mysql-connection-is-ready/45058879
=> Use a SELECT query for mysql healthcheck

lib/buildkite/config/ruby_config.rb, test/buildkite_config/test_rake_command.rb
Now that it's in a separate pipeline, it doesn't make much sense to soft fail it, as it makes it harder to notice ruby-head has failures from the build list.
=> Hard fail ruby nigthly jobs

pipelines/docs-preview/initial.yml, pipelines/docs-preview/pipeline.rb
This PR makes sure the project can exists prior to deploying the pages. Since the Cloudflare Pages UI requires connecting to git, they assume you want to use their builders and create a project with the same name as the repository. However, for this project we want to specifically create a separate pipeline for previews.
Once this PR is merged, there are two remaining tasks:
* Get the `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_API_TOKEN` added to bk agents
* Turn on webhooks in the bk pipeline for github: https://buildkite.com/rails/docs-preview/settings/repository
After this is in place and the first pipeline is deployed, we should be able to remove the `wrangler pages project create` command.
Also, after #95 was merged, we had to update the annotate command given the new location for the …
=> Fix docs-preview pipeline

pipelines/docs-preview/initial.yml, pipelines/docs-preview/pipeline.rb
Note: this is blocked by #99, and rails/rails#51650.
The idea is that we make sure any user-supplied tarball is handled outside of the working directory, in order to avoid any possible shenanigans with `npx`.
I've also removed the approval step so PRs are deployed automatically, since that extra bit of friction was only there to prevent any scenario where a bad actor can obtain the Cloudflare API key and publish malware on a (somewhat official Rails-looking domain) undetected.
=> Move preview tarball outside workdir

pipelines/docs-preview/pipeline.rb
The project was created successfully, so we can remove this part now.
```
✘ [ERROR] A request to the Cloudflare API (/accounts/54aafc02b891b0d13e7e56083770f1af/pages/projects) failed.
A project with this name already exists. Choose a different project name. [code: 8000002]
```
The step still passes (`|| true`), but we don't need this code anymore.
=> Remove create project as initial build succeeded

bin/docs-preview-annotate, pipelines/docs-preview/pipeline.rb
This is to avoid mounting the checkout (of head or branch/PR) when deploying the docs-preview or generating the annotation, as a safety mechanism.
Also added a minor UX improvement to link directly to the API and Guides in the annotation.
=> Avoid mounting checkout for docs-preview and docs-preview-annotate jobs

docker-compose.yml
MySQL 8.4 has this plugin disabled by default, and trilogy already suppoots the new default authentication plugin, so we can now swap to the new default.
=> Remove usage of --default-authentication-plugin=mysql_native_password

lib/buildkite/config/rake_command.rb, lib/buildkite/config/ruby_group.rb, pipelines/rails-ci/pipeline.rb
Buildkite taught me about the `skip` attribute for command steps, so we can avoid allocating an agent just to print "skipping" message.
We also want to make sure linter is still run regardless of the skip attribute. Since it can detect documentation bugs in the guides, changelogs, etc.
This requires the image build always runs.
=> Skip the skip

docker-compose.yml
This commit removes the obsolete `version` from docker-compose.yml
- Steps to reproduce
```ruby
git clone https://github.com/rails/rails
cd rails
git clone https://github.com/rails/buildkite-config .buildkite/
RUBY_IMAGE=ruby:3.3 docker compose -f .buildkite/docker-compose.yml build base
```
- Without this commit, it shows this warning.
```ruby
WARN[0000] /home/yahonda/rails/.buildkite/docker-compose.yml: `version` is obsolete
```
Refer to https://github.com/compose-spec/compose-spec/pull/489
=> Remove `version` that is obsolete

Dockerfile, lib/buildkite/config/ruby_config.rb
This pull request updates Ruby docker images used at Rails Nightly https://buildkite.com/rails/rails-nightly It has two changes:
`rubylang/ruby:master` and `rubylang/ruby:master-debug` images without Ubuntu codename suffix are available since https://github.com/ruby/docker-images/pull/102/files We will not have to update these lines every two years.
Starting from Ubuntu 23.10 some of tzdata package contents moved into `tzdata-legacy` that affects Active Support code as per reported https://github.com/rails/rails/issues/49648 . Ubuntu 24.04 requires the `tzdata-legacy` package while Debian “bookworm” based docker image like `ruby:3.3` does not have `tzdata-legacy` so it installs `tzdata-legacy` package only if available.
This commit have been verified locally:
- rubylang/ruby:master image …
=> Use `rubylang/ruby:master` and `rubylang/ruby:master-debug` image

pipelines/docs-preview/pipeline.rb
The reason for `bundle install` was because the initial PR we used the `ruby:latest` docker image, which doesn't have any dependencies pre-installed.
As such, we needed `BUNDLE_WITHOUT` to prevent installing gems which depend on native extensions also missing from that image.
Since we switched to using a pre-built mainline image, all of the necessary dependencies should be there and we can remove this step to save time.
---
This is hard to test without access to the images on ECR, but I can imagine a possible race-condition where a dependency is changed in the gemfile and a docs-preview build is triggered before that image can reach the cache. It should be rare though, and a rebuild should fix it.
=> Remove bundle install from docs-preview pipeline

lib/buildkite/config/build_context.rb, pipelines/rails-ci/pipeline.rb, test/buildkite_config/test_build_context.rb, test/buildkite_config/test_rake_command.rb
[Add Rack 3.0 jobs](https://github.com/rails/buildkite-config/commit/6b7fa4414431b49a0edd07ca62ece49abc2be912)
Since the release of Rack 3.1, we are now only testing against Rack 2
and Rack 3.1. This is a problem because their are behavioral changes
made between 3.0 and 3.1 (such as `rack.input` now being optional).
To ensure that we stay compatible with all of the versions we claim to
be compatible with, this commit adds actionpack and railties jobs for
Rack 3.0.
---
[Only run extra Rack jobs on Rails 7.1+](https://github.com/rails/buildkite-config/pull/110/commits/0c33b70475010b757fa2830ccd0ecd88365e6d0c)
Rails <= 7.0 does not support Rack 3, so any `rack-3-0` and `rack-head`
jobs will necessarily fail. Additionally, `rack-2` is not needed because
the default jobs are already testing …
=> Add Rack 3.0 jobs, and only run Rack 3+ jobs on Rails 7.1+

pipelines/docs-preview/pipeline.rb
This PR changes the `docs-preview` pipeline to skip when building older stable branches, since the rake task only exists since the 7-2-stable branch.
This job would fail for backport PRs which may be confusing to contributors, and I don't think it's necessary to backport the rake task to show doc previews for bug fixes to <= 7.1. Let's focus on making 7.2+ docs better.
I've also added a timeout of 15 minutes on all steps in this pipeline, since there was none and I found a job which ran over 4 hours: https://buildkite.com/rails/docs-preview/builds/1836#01904172-0201-497e-97e8-e211e2db9561
Whoops!
=> Skip old branches and add timeout

docker-compose.yml
Ref https://github.com/docker-library/mysql/issues/930
There have many many flaky CI runs since the await script was replaced with docker healthchecks. The MySQL service will report a healthy status, but then the test container is unable to connect to it.
There was an attempt [previously][1] to fix this, but that change does not seem to have fixed the issue.
Looking into this issue further has pointed me to a potential cause: the default mysql docker images will boot up mysql twice. The first time it starts up a temporary server for init purposes, and the second time is the "real" mysqld. The current healthcheck doesn't differentiate between the two servers, so it passes even when the "real" server isn't running.
However, we should be able to differentiate the two servers because the init …
=> Fix another issue with mysql healthcheck

lib/buildkite/config/build_context.rb, pipelines/rails-ci/pipeline.rb, test/buildkite_config/test_build_context.rb
Rails 8.0 is currently in beta, likely will be released not long before Ruby 3.4 is, so we want to flush out any compatibility issues so that users can upgrade to Ruby 2.4 in January.
=> Add Ruby 3.4.0-preview2 to CI

lib/buildkite/config/build_context.rb
=> Limit Rails 7.1 and older to Ruby 3.3

lib/buildkite/config/build_context.rb, lib/buildkite/config/rake_command.rb, test/buildkite_config/test_build_context.rb, test/buildkite_config/test_rake_command.rb
I've seen quite a bit of
> Exited with status 255 (after intercepting the agent’s termination signal, sent because the agent was stopped)
On my PRs.
=> Automatically retry on exit code 255

lib/buildkite/config/rake_command.rb, pipelines/rails-ci/pipeline.rb
We see a surprising number of these:
`Error response from daemon: Get "https://973266071021.dkr.ecr.us-east-1.amazonaws.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
We could also consider retrying the whole job on exit code 18, instead of or in addition to this change. For now let's start with the tighter, inline, retry here -- then we can consider checking the exit code if it seems that we sometimes end up with a truly un-network-able agent, rather than a transient blip.
=> Tell the docker-compose plugin to retry pulls a few times

docker-compose.yml
We have to explicitly allow any environment variables we want to pass through to the container.
```
cd ~/code/rails
gh pr checkout 53697
rsync -av --progress /home/zzak/code/buildkite-config/ .buildkite
RUBY_IMAGE="ruby:3.3" docker compose -f .buildkite/docker-compose.yml build base
MYSQL_PREPARED_STATEMENTS=true IMAGE_NAME="buildkite-base" RUBY_IMAGE="ruby:3.3" docker compose -f .buildkite/docker-compose.yml run mysqldb runner activerecord 'rake mysql2:test'
```
Also tested without the env var.
=> Make sure to pass MYSQL_PREPARED_STATEMENTS to container

pipelines/rails-ci/pipeline.rb
This commit uses "mariadb:lts" that is MariaDB Server 11.4 until https://github.com/rails/rails/issues/53727 is resolved.
Refer to
* MariaDB Server 11.4 will be LTS https://mariadb.org/11-4-lts/
=> Use "mariadb:lts" to workaround CI failure

docker-compose.yml
This silences the following errors in my docker logs:
```
postgres-1         | 2024-12-02 02:13:29.359 UTC [85235] FATAL:  role "root" does not exist
postgres-1         | 2024-12-02 02:13:39.415 UTC [85244] FATAL:  role "root" does not exist
postgres-1         | 2024-12-02 02:13:49.475 UTC [85253] FATAL:  role "root" does not exist
postgres-1         | 2024-12-02 02:13:59.519 UTC [85262] FATAL:  role "root" does not exist
```
The default user for this image is `postgres', which we don't change:
https://hub.docker.com/_/postgres
https://github.com/rails/buildkite-config/blob/13b395cd1a6ea11d9505a739826f4ba304562835/docker-compose.yml#L32
=> Use default pg user for healthcheck

docker-compose.yml, mariadb-conf.d/mariadb.cnf, pipelines/rails-ci/pipeline.rb
This commit restores to use the `mariadb:latest` image and disables innodb_snapshot_isolation that is enabled by default since MariaDB 11.6.2 and 11.7.1 because it causes Rails CI failures as per reported https://github.com/rails/rails/issues/53727 .
- MariaDB 11.6.2 Release Notes https://mariadb.com/kb/en/mariadb-11-6-2-release-notes/
- MariaDB 11.7.1 Release Notes https://mariadb.com/kb/en/mariadb-11-7-1-release-notes/
> Defaults change - the innodb_snapshot_isolation system variable now defaults to ON, previously was OFF (MDEV-35124)
https://jira.mariadb.org/browse/MDEV-35124
The `loose` prefix is added to support MariaDB versions that does not have `innodb_snapshot_isolation`. It only exists at MariaDB Server 10.6.18, 10.11.8, 11.4.2 and later versions of MariaDB via …
=> Disable `innodb_snapshot_isolation` for MariaDB

docker-compose.yml, mariadb-conf.d/mariadb.cnf, pipelines/rails-ci/pipeline.rb
Reverts rails/buildkite-config#134
Looks like it doesn't work well.
https://buildkite.com/rails/rails/builds/114641#0193b412-58ee-47e5-94fc-5ef5c614abee/1260-1268
=> Revert "Disable `innodb_snapshot_isolation` for MariaDB"

docker-compose.yml
CI started failing with:
```
manifest for rabbitmq:alpine not found
```
It's unclear what's going on given this label is still displayed on https://hub.docker.com/_/rabbitmq.
But trying a sligthly more specific label might fix it.
=> Change the rabbitmq image

docker-compose.yml
Reverts rails/buildkite-config#138
I messed the image URL, which cause CI to soft fails, hence why I thought it worked....
=> Revert "Change the rabbitmq image"

pipelines/rails-ci/pipeline.rb
This pull request adds Ruby 3.4 image to Rails CI
`ruby:3.4` tag is available.
https://hub.docker.com/layers/library/ruby/3.4/images/sha256-91a6accf150fcb98a5fc3873b1e5c2c3008e39408edb8cb2cebe58a7cde2ce91
=> Add Ruby 3.4 image to Rails CI

pipelines/rails-ci/pipeline.rb
This commit addresses Rails CI failures https://buildkite.com/rails/rails/builds/119085#01975d87-fe6b-4b0d-8178-0430a34f3376/1283-1291 That is related to https://github.com/rails/rails/issues/53727
To workaround it, docker image tag has been changed from `mariadb:latest` to `mariadb:lts` via https://github.com/rails/buildkite-config/pull/130. At that time `mariadb:lts` uses MariaDB 11.4.
Now `mariadb:lts` image now uses MariaDB 11.8 via https://github.com/MariaDB/mariadb-docker/blob/4c5048803b4785a1ef057c2d4c48b126a08348c6/11.8/Dockerfile We will need to use `mariadb:11.4` that is the previous versions of MariaDB lts that should not be affected by https://github.com/rails/rails/issues/53727
=> Use "mariadb:11.4" to workaround CI failure

Dockerfile
Debian removed `apt-key`.
FYI: @yahonda
=> Fix compatibility with debian trixie based images

docker-compose.yml
@buildkite is experimenting with moving rails/rails CI to hosted agents. During this migration, we discovered that the beanstalkd container health check fails on hosted agents. We suspect this is due to a difference in how `localhost` resolves between environments. On self-hosted agents, `localhost` resolves to IPv4 (`127.0.0.1`), but on hosted agents it appears to resolve to IPv6 (`::1`). Since beanstalkd only listens on IPv4, `nc localhost 11300` attempts an IPv6 connection which fails. We were able to replicate this failure locally and confirmed that explicitly using `127.0.0.1` resolves it. This change updates the beanstalkd health check to force IPv4 resolution, and also updates the chrome container health check for consistency with the other containers which already use `127.0.0.1`.
=> Explicitly use IPv4 in beanstalkd, chrome container health checks
